### ISSUE TITLE
module 3 phase 3

### ISSUE THREAD

**Issue by Afify21** [Pulsify-dev/Cross#9]
🚨 Module 3: Social & Graph Feed Defect Report
Fatal Build Failure (_, _): The application inherently crashes during staging compilation. The Cross team used overlapping wildcard syntax (_, _) inside six distinct widget files (e.g., followers_screen.dart, mutual_followers_screen.dart). This is illegal in Dart 3.0+ and immediately crashes the QA build pipeline! (I had to forcefully overwrite them via CLI just to get the testing started).
Graph State Bleeding: During social-graph.spec.js polling, rapidly toggling Follow/Unfollow elements causes sync delays. The local provider state often lags behind the UI thread, causing tests to record stale Follower numbers on the public profile screen.

ssue 1: Fatal Dart Compilation Overlap
Title: [BUG] Fatal App Compilation Error: "_" is already declared in this scope (Dart SDK 3.0+)

Description: Describe the bug: The application fails to compile using flutter build apk on Dart SDK v3.0+. Several files within the application are utilizing (_, _) overlapping wildcard parameters inside separatorBuilder widgets. Modern Dart compliance rejects identical scoping names.

Steps to Reproduce:

Upgrade to Dart >=3.0.0
Run flutter build apk --debug
Observe compilation exit code 1.
Error Logs:

text
lib/features/profile/screens/followers_screen.dart:113:43: Error: '_' is already declared in this scope.
                    separatorBuilder: (_, _) => const SizedBox(height: 10),
lib/features/social/screens/mutual_followers_screen.dart:88:43: Error: '_' is already declared in this scope.
Proposed Fix: Migrate the dual overlapping wildcards to distinct ignore flags: (_, __) => ... in all separatorBuilder callbacks natively.
